language: php
php:
  - '7.0'
  - hhvm
  - nightly

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - composer self-update
  - composer install
  - mysql -e "create database IF NOT EXISTS test;" -uroot

script: ./vendor/bin/phpunit